version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
      - image: circleci/postgres:9.4.12-alpine

    steps:
      - checkout

      # Restore bundle cache, install new gems and store bundle cache
      - type: cache-restore
        key: app-{{ checksum "Gemfile.lock" }}

      - run: bundle install
      - type: cache-save
        key: app-{{ checksum "Gemfile.lock" }}
        paths:
          - .bundle

      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      - type: shell
        command: bundle exec rspec

  test:

  deploy:
