default: &default
  google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>
  google_api_secret: <%= ENV["GOOGLE_API_KEY"] %>
  foursquare_client_id: <%= ENV["FOURSQUARE_CLIENT_ID"] %>
  foursquare_client_secret: <%= ENV["FOURSQUARE_CLIENT_SECRET"] %>

development:
  <<: *default
  secret_key_base: e2a2aaeca31981d4fbb4cd066263409e2a8fc503439c9137c0a610e3a07136345fda10c4548a6364471180adfff055d7cf689b403d3a7b788676618000156c8c


test:
  secret_key_base: 592265cca5ab75611978eecf0493c7c6da1d2aaf42017695da15fffe0dd646b22fdc4c7ecf367783801e38dd749fa7e79d48e282ca8b1a79e683617fc94cf787

production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
